version: 1
services:
  backend:
    build:
      context: ./backend
      builder: buildpack
      args:
        - PYTHON_VERSION=3.11
    env:
      - key: PORT
        value: "8003"
      - key: ENVIRONMENT
        value: "production"
      - key: FASTAPI_PORT
        value: "8003"
    ports:
      - "8003:8003"
    healthcheck:
      path: /health
      interval: 10
    restart: always
    type: web
    instance_type: nano
    min_scale: 1
    max_scale: 1
    regions: ["was"]

  frontend:
    build:
      context: ./frontend
      builder: buildpack
      args:
        - PYTHON_VERSION=3.11
    env:
      - key: PORT
        value: "5175"
      - key: ENVIRONMENT
        value: "production"
      - key: VITE_API_URL
        value: "https://backend-email-knowledge-base-2.koyeb.app"
    ports:
      - "5175:80"
    healthcheck:
      path: /
      interval: 10
    restart: always
    type: web
    instance_type: nano
    min_scale: 1
    max_scale: 1
    regions: ["was"]
