app:
  name: email-knowledge-base

services:
  - name: backend-service
    instance_type: nano
    instance_count: 1
    git:
      repository: kianwoon/email-knowledge-base
      branch: main
    build:
      builder: python
      command: cd backend && pip install -r requirements.txt
    run:
      command: cd backend && PYTHONPATH=$PYTHONPATH:. python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    env:
      - name: PORT
        value: "8000"
      - name: HOST
        value: "0.0.0.0"
      - name: ENVIRONMENT
        value: "production"
      - name: MS_CLIENT_ID
        value: "a4b11a39-ee9e-42b6-ab30-788ccef14d89"
      - name: MS_TENANT_ID
        value: "fda15b03-7d0b-4604-b6a0-00a0712abcf5"
      - name: MS_CLIENT_SECRET
        secret: MS_CLIENT_SECRET
      - name: FRONTEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - name: BACKEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api"
      - name: MS_REDIRECT_URI
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api/auth/callback"
      - name: JWT_SECRET
        value: "production_secret_key_123"
      - name: DEBUG
        value: "true"
    health_check:
      port: 8000
      path: /health
      initial_delay: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    restart_policy:
      type: on-failure
      max_retries: 10
    public: true
    routes:
      - path: /api
        port: 8000

  - name: frontend-service
    instance_type: nano
    instance_count: 1
    git:
      repository: kianwoon/email-knowledge-base
      branch: main
    build:
      builder: nodejs
      command: cd frontend && npm install && VITE_API_BASE_URL=https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api npm run build
    run:
      command: cd frontend && npm run preview -- --host
    env:
      - name: PORT
        value: "3000"
      - name: HOST
        value: "0.0.0.0"
      - name: VITE_API_BASE_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api"
    routes:
      - path: /
        port: 3000
    public: true
