version: 1
services:
  backend-service:
    build:
      context: ./backend
      builder: buildpack
      args:
        - PYTHON_VERSION=3.11
    env:
      - key: PORT
        value: "8000"
      - key: ENVIRONMENT
        value: "production"
      - key: MS_CLIENT_ID
        value: "a4b11a39-ee9e-42b6-ab30-788ccef14d89"
      - key: MS_TENANT_ID
        value: "fda15b03-7d0b-4604-b6a0-00a0712abcf5"
      - key: FRONTEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - key: BACKEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - key: MS_REDIRECT_URI
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api/auth/callback"
      - key: IS_KOYEB
        value: "true"
    ports:
      - "8000:8000"
    healthcheck:
      path: /health
      interval: 10
    restart: always
    type: web
    instance_type: nano
    min_scale: 1
    max_scale: 1
    regions: ["was"]
    routes:
      - path: /api/*
        port: 8000
        priority: 1

  frontend-service:
    build:
      context: ./frontend
      builder: docker
    env:
      - key: ENVIRONMENT
        value: "production"
      - key: VITE_API_BASE_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api"
    ports:
      - "80:80"
    healthcheck:
      path: /
      interval: 10
    restart: always
    type: web
    instance_type: nano
    min_scale: 1
    max_scale: 1
    regions: ["was"]
    routes:
      - path: /*
        port: 80
        priority: 2
