app:
  name: email-knowledge-base

services:
  - name: backend-service
    instance_type: nano
    instance_count: 1
    git:
      repository: kianwoon/email-knowledge-base
      branch: main
    build:
      dockerfile: backend/Dockerfile
    env:
      - name: PORT
        value: "8000"
      - name: HOST
        value: "0.0.0.0"
      - name: ENVIRONMENT
        value: "production"
      - name: MS_CLIENT_ID
        value: "a4b11a39-ee9e-42b6-ab30-788ccef14d89"
      - name: MS_TENANT_ID
        value: "fda15b03-7d0b-4604-b6a0-00a0712abcf5"
      - name: MS_CLIENT_SECRET
        secret: MS_CLIENT_SECRET
      - name: FRONTEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - name: BACKEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - name: MS_REDIRECT_URI
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api/auth/callback"
      - name: JWT_SECRET
        secret: JWT_SECRET
      - name: DEBUG
        value: "true"
      - name: MS_AUTH_BASE_URL
        secret: MS_AUTH_BASE_URL
      - name: MS_SCOPE_STR
        secret: MS_SCOPE
      - name: MS_GRAPH_BASE_URL
        secret: MS_GRAPH_BASE_URL
      - name: JWT_ALGORITHM
        secret: JWT_ALGORITHM
      - name: JWT_EXPIRATION
        secret: JWT_EXPIRATION
      - name: OPENAI_API_KEY
        secret: OPENAI_API_KEY
      - name: EMBEDDING_MODEL
        secret: EMBEDDING_MODEL
      - name: EMBEDDING_DIMENSION
        secret: EMBEDDING_DIMENSION
      - name: QDRANT_URL
        secret: QDRANT_URL
      - name: QDRANT_API_KEY
        secret: QDRANT_API_KEY
      - name: QDRANT_COLLECTION_NAME
        secret: QDRANT_COLLECTION_NAME
      - name: MAX_PREVIEW_EMAILS
        secret: MAX_PREVIEW_EMAILS
      - name: APP_AWS_ACCESS_KEY_ID
        secret: APP_AWS_ACCESS_KEY_ID
      - name: APP_AWS_SECRET_ACCESS_KEY
        secret: APP_AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        secret: AWS_REGION
      - name: EXTERNAL_ANALYSIS_URL
        secret: EXTERNAL_ANALYSIS_URL
      - name: EXTERNAL_ANALYSIS_API_KEY
        secret: EXTERNAL_ANALYSIS_API_KEY
      - name: CORS_ALLOWED_ORIGINS_STR
        secret: CORS_ALLOWED_ORIGINS
      - name: WEBHOOK_PREFIX
        secret: WEBHOOK_PREFIX
      - name: EXTERNAL_WEBHOOK_BASE_URL
        secret: EXTERNAL_WEBHOOK_BASE_URL
      - name: ALLOWED_REDIRECT_DOMAINS_STR
        secret: ALLOWED_REDIRECT_DOMAINS
      - name: ENCRYPTION_KEY
        secret: ENCRYPTION_KEY
      - name: SQLALCHEMY_DATABASE_URI
        secret: SQLALCHEMY_DATABASE_URI
      - name: CELERY_BROKER_URL
        secret: CELERY_BROKER_URL
      - name: CELERY_RESULT_BACKEND
        secret: CELERY_RESULT_BACKEND
    health_check:
      port: 8000
      path: /api/health
      initial_delay: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    restart_policy:
      type: on-failure
      max_retries: 10
    public: true
    routes:
      - path: /api/*
        port: 8000

  - name: frontend-service
    instance_type: nano
    instance_count: 1
    git:
      repository: kianwoon/email-knowledge-base
      branch: main
    build:
      builder: nodejs
      command: cd frontend && npm install && npm run build
      env:
        - name: VITE_API_BASE_URL
          value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api"
        - name: VITE_BACKEND_URL
          value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
    run:
      command: cd frontend && npm run preview -- --host
    env:
      - name: PORT
        value: "3000"
      - name: HOST
        value: "0.0.0.0"
      - name: VITE_API_BASE_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api"
      - name: VITE_BACKEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
    routes:
      - path: /
        port: 3000
    public: true

  - name: celery-worker
    instance_type: nano  # Adjust instance type as needed
    instance_count: 1    # Adjust count as needed
    git:
      repository: kianwoon/email-knowledge-base
      branch: main
    build:
      dockerfile: backend/Dockerfile.worker
    # No 'run' command needed here, as CMD is in the Dockerfile
    env:
      # Copy relevant environment variables from backend-service
      - name: ENVIRONMENT
        value: "production"
      - name: MS_CLIENT_ID
        value: "a4b11a39-ee9e-42b6-ab30-788ccef14d89" # Consider using secrets
      - name: MS_TENANT_ID
        value: "fda15b03-7d0b-4604-b6a0-00a0712abcf5" # Consider using secrets
      - name: MS_CLIENT_SECRET
        secret: MS_CLIENT_SECRET
      - name: FRONTEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - name: BACKEND_URL
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app"
      - name: MS_REDIRECT_URI
        value: "https://email-knowledge-base-2-automationtesting-ba741710.koyeb.app/api/auth/callback"
      - name: JWT_SECRET
        secret: JWT_SECRET
      - name: DEBUG
        value: "false" # Consider setting to false for production workers
      # Add other environment variables needed by Celery tasks (e.g., Broker/Backend URLs)
      # Ensure these match what's configured in backend/app/celery_app.py
      - name: CELERY_BROKER_URL
        secret: CELERY_BROKER_URL # Make sure this secret exists in Koyeb
      - name: CELERY_RESULT_BACKEND
        secret: CELERY_RESULT_BACKEND # Make sure this secret exists in Koyeb
    restart_policy:
      type: on-failure
      max_retries: 10
