"""Add azure_blob_sync_items table

Revision ID: 1c5ed067b3e2
Revises: d1c9abde3212
Create Date: 2025-04-14 16:03:28.629199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c5ed067b3e2'
down_revision: Union[str, None] = 'd1c9abde3212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_blob_sync_items', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('azure_blob_sync_items', 'item_type',
               existing_type=postgresql.ENUM('BLOB', 'PREFIX', name='azureblobsyncitemtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('azure_blob_sync_items', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='azureblobsyncstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_azure_blob_sync_items_container_name'), 'azure_blob_sync_items', ['container_name'], unique=False)
    op.create_index(op.f('ix_azure_blob_sync_items_user_id'), 'azure_blob_sync_items', ['user_id'], unique=False)
    op.create_index('ix_azure_sync_items_connection_status', 'azure_blob_sync_items', ['connection_id', 'status'], unique=False)
    op.create_index('ix_azure_sync_items_user_status', 'azure_blob_sync_items', ['user_id', 'status'], unique=False)
    op.create_unique_constraint('uq_azure_connection_item_path', 'azure_blob_sync_items', ['connection_id', 'item_path'])
    op.create_foreign_key(None, 'azure_blob_sync_items', 'users', ['user_id'], ['id'])
    op.drop_column('azure_blob_sync_items', 'created_at')
    op.drop_column('azure_blob_sync_items', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_blob_sync_items', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('azure_blob_sync_items', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'azure_blob_sync_items', type_='foreignkey')
    op.drop_constraint('uq_azure_connection_item_path', 'azure_blob_sync_items', type_='unique')
    op.drop_index('ix_azure_sync_items_user_status', table_name='azure_blob_sync_items')
    op.drop_index('ix_azure_sync_items_connection_status', table_name='azure_blob_sync_items')
    op.drop_index(op.f('ix_azure_blob_sync_items_user_id'), table_name='azure_blob_sync_items')
    op.drop_index(op.f('ix_azure_blob_sync_items_container_name'), table_name='azure_blob_sync_items')
    op.alter_column('azure_blob_sync_items', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='azureblobsyncstatus'),
               existing_nullable=False)
    op.alter_column('azure_blob_sync_items', 'item_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BLOB', 'PREFIX', name='azureblobsyncitemtype'),
               existing_nullable=False)
    op.drop_column('azure_blob_sync_items', 'user_id')
    # ### end Alembic commands ###
