"""Make account_name nullable in azure_blob_connections

Revision ID: 683446c2aab8
Revises: f51ab72adcfd
Create Date: 2025-04-14 19:32:18.822419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683446c2aab8'
down_revision: Union[str, None] = 'f51ab72adcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('azure_blob_connections', 'account_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('azure_blob_connections', 'account_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
