"""Add account_key column to azure_blob_connections

Revision ID: 7825d450f39e
Revises: 1c5ed067b3e2
Create Date: 2025-04-14 19:12:33.490523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7825d450f39e'
down_revision: Union[str, None] = '1c5ed067b3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_blob_connections', sa.Column('account_key', sa.Text(), nullable=True))
    op.alter_column('azure_blob_connections', 'credentials',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('azure_blob_connections', 'credentials',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('azure_blob_connections', 'account_key')
    # ### end Alembic commands ###
