"""Add allow_topics and deny_topics to TokenDB

Revision ID: 7e6667be8ba3
Revises: eba4c0081618
Create Date: 2025-04-09 17:17:46.757197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e6667be8ba3'
down_revision: Union[str, None] = 'eba4c0081618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tokens_hashed_token', table_name='tokens')
    op.drop_index('ix_tokens_owner_email', table_name='tokens')
    op.drop_table('tokens')
    op.alter_column('users', 'ms_refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'ms_refresh_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashed_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sensitivity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_editable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('deny_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.create_index('ix_tokens_owner_email', 'tokens', ['owner_email'], unique=False)
    op.create_index('ix_tokens_hashed_token', 'tokens', ['hashed_token'], unique=True)
    # ### end Alembic commands ###
