"""Add status to SharePointSyncItem

Revision ID: b979c2d1c1a8
Revises: b99a740d329f
Create Date: 2025-04-12 22:02:35.055289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b979c2d1c1a8'
down_revision: Union[str, None] = 'b99a740d329f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharepoint_sync_items', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_sharepoint_sync_items_status'), 'sharepoint_sync_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharepoint_sync_items_status'), table_name='sharepoint_sync_items')
    op.drop_column('sharepoint_sync_items', 'status')
    # ### end Alembic commands ###
