"""Add role_arn to aws_credentials

Revision ID: dd596da5145c
Revises: b979c2d1c1a8
Create Date: 2025-04-13 19:29:30.382413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd596da5145c'
down_revision: Union[str, None] = 'b979c2d1c1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aws_credentials_id', table_name='aws_credentials')
    op.drop_index('ix_aws_credentials_user_email', table_name='aws_credentials')
    op.drop_table('aws_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('aws_access_key_id_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('aws_secret_access_key_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('aws_region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='aws_credentials_user_email_fkey'),
    sa.PrimaryKeyConstraint('id', name='aws_credentials_pkey')
    )
    op.create_index('ix_aws_credentials_user_email', 'aws_credentials', ['user_email'], unique=True)
    op.create_index('ix_aws_credentials_id', 'aws_credentials', ['id'], unique=False)
    # ### end Alembic commands ###
