"""Add last_kb_task_id column to users table

Revision ID: eba4c0081618
Revises: 
Create Date: 2025-04-09 17:08:26.866548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba4c0081618'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_kb_task_id', sa.String(), nullable=True, index=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_kb_task_id'), table_name='users') # Drop index first
    op.drop_column('users', 'last_kb_task_id')
    # ### end Alembic commands ###
