"""Remove account_key column from azure_blob_connections

Revision ID: f51ab72adcfd
Revises: 7825d450f39e
Create Date: 2025-04-14 19:29:41.488991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51ab72adcfd'
down_revision: Union[str, None] = '7825d450f39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cache_data_expires_at_idx', table_name='cache_data')
    op.drop_table('cache_data')
    op.alter_column('azure_blob_connections', 'credentials',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('azure_blob_connections', 'account_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_blob_connections', sa.Column('account_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('azure_blob_connections', 'credentials',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('cache_data',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='cache_data_pkey')
    )
    op.create_index('cache_data_expires_at_idx', 'cache_data', ['expires_at'], unique=False)
    # ### end Alembic commands ###
