# Trigger deployment of a Koyeb app when changes are pushed to the main branch
name: Deploy Koyeb App Official

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.koyeb.yml'

jobs:
  deploy:
    name: Deploy Services
    runs-on: ubuntu-22.04
    env:
      KOYEB_APP_NAME: ${{ secrets.KOYEB_APP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for worker-related backend changes
        id: changed_worker_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/services/**
            backend/tasks/**
            backend/requirements.txt
            backend/app/celery_app.py
            backend/app/config.py

      - name: Check for frontend changes
        id: changed_frontend_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            frontend/**

      - name: Check for backend changes
        id: changed_backend_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
            !backend/services/**
            !backend/tasks/**
            !backend/requirements.txt
            !backend/app/celery_app.py
            !backend/app/config.py

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Redeploy Backend Service
        if: steps.changed_backend_files.outputs.any_changed == 'true'
        run: |
          koyeb service redeploy email-knowledge-base-2/backend-service

      - name: Redeploy Frontend Service
        if: steps.changed_frontend_files.outputs.any_changed == 'true'
        run: |
          koyeb service redeploy email-knowledge-base-2/frontend-service

      - name: Redeploy Celery Worker
        if: steps.changed_worker_files.outputs.any_changed == 'true'
        run: |
          koyeb service redeploy email-knowledge-base-2/celery-worker