# Trigger deployment of a Koyeb app when changes are pushed to the main branch
name: Deploy Koyeb App Official

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.koyeb.yml'

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools && pip install -r backend/requirements.txt
      - name: Run Backend Tests
        run: pytest backend/

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: |
            frontend/node_modules
            frontend/.cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy:
    name: Deploy Services
    needs:
      - build-backend
      - build-frontend
    runs-on: ubuntu-22.04
    concurrency:
      group: deploy-${{ github.ref }}-${{ matrix.service }}
      cancel-in-progress: true
    strategy:
      matrix:
        service:
          - backend-service
          - frontend-service
          - celery-worker
    env:
      KOYEB_APP_NAME: ${{ secrets.KOYEB_APP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for worker-related backend changes
        id: changed_worker_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/services/**
            backend/tasks/**
            backend/requirements.txt
            backend/app/celery_app.py
            backend/app/config.py

      - name: Check for frontend changes
        id: changed_frontend_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            frontend/**

      - name: Check for backend changes
        id: changed_backend_files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
            !backend/services/**
            !backend/tasks/**
            !backend/requirements.txt
            !backend/app/celery_app.py
            !backend/app/config.py

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Redeploy Service
        if: |
          (matrix.service == 'backend-service' && steps.changed_backend_files.outputs.any_changed == 'true') ||
          (matrix.service == 'frontend-service' && steps.changed_frontend_files.outputs.any_changed == 'true') ||
          (matrix.service == 'celery-worker' && steps.changed_worker_files.outputs.any_changed == 'true')
        uses: ./.github/actions/redeploy
        with:
          service: ${{ matrix.service }}

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          fields: repo,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}