name: Deploy Celery Worker to Koyeb

# Trigger this workflow only when changes are pushed to the main branch
# AND affect files relevant to the Celery worker
on:
  push:
    branches:
      - main  # This ensures the deployment only triggers when changes are pushed to the 'main' branch
    paths:
      - 'backend/Dockerfile.worker'
      - 'backend/celery_app.py'
      - 'backend/tasks/**'
      - 'backend/requirements.txt'
      - 'backend/app/config.py'
      - 'backend/app/db/**'
      - 'backend/app/crud/**'
      - 'backend/app/models/**'
      - 'backend/app/services/**'
      - 'backend/app/utils/**'

jobs:
  deploy-worker:
    name: Deploy Celery Worker Service
    runs-on: ubuntu-latest

    steps:
      # Explicitly checkout the code to ensure the runner sees the latest workflow file
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use the official Koyeb Deploy Action with the newly created tag
      - name: Trigger Koyeb Service Redeployment
        uses: koyeb/action-deploy@v1   # Use the 'v1' tag you created
        with:
          koyeb_api_token: ${{ secrets.KOYEB_API_TOKEN }}
          app: ${{ secrets.KOYEB_APP_NAME }}
          service: 'celery-worker'
          # Optional: Add a message to the deployment history on Koyeb
          # message: "Deploying Celery worker triggered by commit ${{ github.sha }}"
