name: Deploy Celery Worker to Koyeb

on:
  push:
    branches:
      - main
    paths:
      - 'backend/Dockerfile.worker'
      - 'backend/celery_app.py'
      - 'backend/tasks/**'
      - 'backend/requirements.txt'
      - 'backend/app/config.py'
      - 'backend/app/db/**'
      - 'backend/app/crud/**'
      - 'backend/app/models/**'
      - 'backend/app/services/**'
      - 'backend/app/utils/**'

jobs:
  deploy-worker:
    name: Deploy Celery Worker Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging Info (Optional)
        run: |
          echo "Koyeb API Token: ${{ secrets.KOYEB_API_TOKEN }}"
          echo "Koyeb App Name: ${{ secrets.KOYEB_APP_NAME }}"

      - name: Trigger Koyeb Service Redeployment
        uses: koyeb/action-deploy@main  # Use 'main' if 'v1' causes issues
        with:
          koyeb_api_token: ${{ secrets.KOYEB_API_TOKEN }}
          app: ${{ secrets.KOYEB_APP_NAME }}
          service: 'celery-worker'
          # Optional: Add a message to the deployment history on Koyeb
          # message: "Deploying Celery worker triggered by commit ${{ github.sha }}"
