name: Deploy Celery Worker to Koyeb

# Trigger this workflow only when changes are pushed to the main branch
# AND affect files relevant to the Celery worker
on:
  push:
    branches:
      - main  # Or change to your primary deployment branch if different
    paths:
      - 'backend/Dockerfile.worker'
      - 'backend/celery_app.py'
      - 'backend/tasks/**'
      - 'backend/requirements.txt'
      - 'backend/app/config.py'
      - 'backend/app/db/**'
      - 'backend/app/crud/**'
      - 'backend/app/models/**'
      - 'backend/app/services/**'
      - 'backend/app/utils/**'

jobs:
  build:
    name: Build and Test Celery Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies (Optional: If you need to install requirements)
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      # Run Tests (Optional: Only if you have a test suite for the worker)
      - name: Run Tests
        run: |
          pytest tests/

  deploy:
    name: Deploy Celery Worker Service
    needs: build  # Ensure deployment only happens after successful build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Koyeb Service Redeployment
        uses: koyeb/action-deploy@v2
        with:
          koyeb_api_token: ${{ secrets.KOYEB_API_TOKEN }}
          app: ${{ secrets.KOYEB_APP_NAME }}
          service: 'celery-worker'
          # Uncomment the line below if you want to add a custom message
          # message: "Deploying Celery worker triggered by commit ${{ github.sha }}"

      # Optional: Add rollback in case of failure (Example)
      - name: Rollback Deployment
        if: failure()
        run: |
          echo "Deployment failed. Rolling back."
          koyeb action rollback --app ${{ secrets.KOYEB_APP_NAME }} --service celery-worker
