name: Deploy to Koyeb on Change

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      # Trigger workflow if ANY relevant code/config changes:
      - 'frontend/**'             # Added frontend path
      - 'backend/**'              # Broadened backend path
      # Removed specific backend paths as they are covered by backend/**
      - '.koyeb.yml'                # Koyeb configuration changes

jobs:
  deploy:
    name: Redeploy Koyeb Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Removed Python setup, pip upgrade, and CLI install steps

      # Use curl to trigger deployment via Koyeb API
      - name: Trigger Koyeb Deployment via API
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
          KOYEB_APP_NAME: ${{ secrets.KOYEB_APP_NAME }} # Use the app name secret
        run: |
          echo "Triggering deployment for app: $KOYEB_APP_NAME"
          DEPLOY_URL="https://app.koyeb.com/v1/apps/$KOYEB_APP_NAME/deployments"
          echo "Calling URL: $DEPLOY_URL"
          
          # Note: This API call might just trigger a deployment based on the app's existing Git settings.
          # It might not explicitly force a build like the CLI command did.
          # Check Koyeb API docs if more specific control (like force build) is needed via API.
          curl -s -X POST $DEPLOY_URL \
            -H "Authorization: Bearer $KOYEB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"git": {"branch": "main"}}' # Trigger deployment from main branch
          
          echo "Deployment trigger request sent."

      # Optionally add a message:
      # message: "Deploy triggered by commit ${{ github.sha }} on ${{ github.ref_name }}" 