name: Deploy to Koyeb on Change

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      # Trigger workflow if ANY relevant code/config changes:
      - 'frontend/**'             # Added frontend path
      - 'backend/**'              # Broadened backend path
      # Removed specific backend paths as they are covered by backend/**
      - '.koyeb.yml'                # Koyeb configuration changes

jobs:
  deploy:
    name: Redeploy Koyeb Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip & Install setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install Koyeb CLI from GitHub
        run: pip install git+https://github.com/koyeb/koyeb-cli.git

      - name: Trigger Koyeb Deployment
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: koyeb apps deploy ${{ secrets.KOYEB_APP_NAME }} --git-branch main --force-build

      # Optionally add a message:
      # message: "Deploy triggered by commit ${{ github.sha }} on ${{ github.ref_name }}" 