name: Deploy to Koyeb on Change

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      # Trigger workflow if ANY relevant code/config changes:
      - 'frontend/**'             # Added frontend path
      - 'backend/**'              # Broadened backend path
      # Removed specific backend paths as they are covered by backend/**
      - '.koyeb.yml'                # Koyeb configuration changes

jobs:
  deploy:
    name: Redeploy Koyeb Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Koyeb CLI
        run: pip install -v koyeb-cli

      - name: Trigger Koyeb Deployment
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }} # Store your Koyeb API token as a GitHub Secret
        # This command re-deploys the entire app based on the latest commit
        # which will rebuild and restart services as needed according to .koyeb.yml
        run: koyeb apps deploy email-knowledge-base --git-branch main --force-build 