name: Deploy to Koyeb on Change

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      # Trigger workflow if ANY relevant code/config changes:
      - 'frontend/**'             # Added frontend path
      - 'backend/**'              # Broadened backend path
      # Removed specific backend paths as they are covered by backend/**
      - '.koyeb.yml'                # Koyeb configuration changes

jobs:
  deploy:
    name: Redeploy Koyeb Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Koyeb App Deployment
        uses: koyeb/action-deploy@v2
        with:
          koyeb_api_token: ${{ secrets.KOYEB_API_TOKEN }}
          app: ${{ secrets.KOYEB_APP_NAME }}
          # By default, the action deploys the app based on the latest commit,
          # matching the behavior of 'koyeb apps deploy'. No need to specify service.
          # Optionally add a message:
          # message: "Deploy triggered by commit ${{ github.sha }} on ${{ github.ref_name }}" 