name: Deploy to Koyeb on Change (Service Redeploy Attempt)

on:
  push:
    branches:
      - main # Or your primary deployment branch
    paths:
      # Trigger workflow if ANY relevant code/config changes:
      - 'frontend/**'             # Still trigger for frontend changes (Koyeb figures it out)
      - 'backend/**'              # Broadened backend path
      - '.koyeb.yml'                # Koyeb configuration changes

jobs:
  deploy:
    name: Redeploy Koyeb Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Re-add Python setup and CLI install
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip & Install setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install Koyeb CLI from GitHub
        run: pip install git+https://github.com/koyeb/koyeb-cli.git

      # Login to Koyeb CLI
      - name: Login to Koyeb CLI
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: koyeb login --token $KOYEB_TOKEN

      # Trigger specific service redeploys
      # Note: Add more services here if needed
      - name: Redeploy Backend Service
        env:
          KOYEB_APP_NAME: ${{ secrets.KOYEB_APP_NAME }}
        run: koyeb service redeploy $KOYEB_APP_NAME/backend-service

      - name: Redeploy Celery Worker Service
        env:
          KOYEB_APP_NAME: ${{ secrets.KOYEB_APP_NAME }}
        run: koyeb service redeploy $KOYEB_APP_NAME/celery-worker 